define({
	root : ({
		_widgetLabel : "eDraw",
		yes:"Si",
		yes:"Si",
		no:"No",
		selectDrawMode : "Seleccionar modo de dibujo",
		clear : "Borrar",
		point : "Punto",
		line : "Línea",
		polyline: "Polilínea",
	    freehandPolyline: "Polilínea a mano alzada",
	    triangle: "Triángulo",
	    extent: "Contorno",
	    circle: "Círculo",
	    ellipse: "Elipse",
	    polygon: "Polígono",
		freehandPolygon : "Polígono a mano alzada",
		text : "Texto",
		textWarningMessage : "El texto debe estar escrito antes de colocar el punto en el mapa",
		style: "Estilo",
	    alpha: "Transparencia",
	    width: "Ancho",
	    size: "Tamaño",
	    color: "Color",
	    markerColor: "Color del marcador",
	    outlineColor: "Color del contorno",
	    lineColor: "Color de línea",
	    fillColor: "Color de relleno",
		showMeasurements : "Mostrar medidas",
		areaUnits : "Unidades de área",
		distanceUnits : "Unidades de distancia",
		pointUnits : "Unidades de punto",
		unitMap : "Unidades de mapa",
		unitDMS : "Degres Minutes Seconds Unit",
		unitDD : "Unidad de Grados Decimales",
		kilometers: "Kilometers",
		miles : "Millas",
		meters : "Metros",
		nauticals : "Millas nauticas",
		feet : "Pies",
		yards : "Yardas",
		squareKilometers : "Kilómetros cuadrados",
		squareMiles : "Millas cuadradas",
		acres : "Acres",
		hectares : "Hectáreas",
		squareMeters : "Metros cuadrados",
		squareFeet: "Pies cuadrados",
    	squareYards: "Yardas cuadradas",
		confirmDrawDelete : "¿Eliminar este dibujo?",
		confirmDrawCheckedDelete : "¿Eliminar dibujo marcado?",
		all : "Todas",
		draws : 'Dibujos',
		addDrawTitle : 'Agregar un dibujo',
		editDrawTitle : 'Editar un dibujo',
		listDrawTitle : 'Lista de dibujos',
		importExportTitle : 'Importar o exportar dibujos',
		exportTitle : "Exportar dibujos",
		importTitle : "Importar dibujos",
		importErrorMessageNavigator : "Su navegador no soporta la funcionalidad.",
		importErrorWarningSelectFile : "Por favor seleccione un archivo.",
		importDragAndDropMessage : "Seleccione un archivo de entrada o arrastre y suelte un archivo en esta área.",
		importWarningNoDrawings : "No hay dibujos para cargar",
		importErrorFileStructure : "La estructura del archivo no coincide.",
		importWarningNoExport0Draw : "Debe seleccionar al menos un dibujo para exportar.",
		importCloseButton:"Cerrar",
		nameField : "Nombre",
		symbolField : "Símbolo",
		nameFieldDefaultValue : "Mi dibujo",
		descriptionField : "Descripción",
		localLoading : "Tus últimos dibujos fueron cargados",
		editLabel : "Actualiza este dibujo",
		deleteLabel : "Elimina este dibujo",
		upLabel : "Mueve este dibujo hacia arriba",
		downLabel : "Mueve este dibujo hacia abajo",
		zoomLabel : "Zoom sobre este dibujo",
		zoomAllLabel : "Zoom en dibujos seleccionados",
		copyLabel : "Copiar dibujos seleccionados",
		copySuffix : " (copy)",
		deleteAllLabel : "Eliminar dibujos seleccionados",
		exportLabel : "Exportar dibujos seleccionados",
		noSelection : "No hay dibujos seleccionados",
		saveButton : "Guardar",
		resetButton : "Reiniciar",
		cancelButton : "Cancelar",
		textAngle : 'Ángulo de texto',
		fontName : 'Nombre de fuente',
		drawSampleRotatedText : 'ángulo',
		boldTitle : 'Bold',
		boldCharacter : 'B',
		italicTitle : 'Italic',
		italicCharacter : 'I',
		underlineTitle : 'Underline',
		underlineCharacter : 'U',
		addMessage : 'Ahora puedes hacer tu dibujo en el mapa',
		editMessage : 'NB : puedes modificar / mover geometría en el mapa',
		snappingMessage : 'NB : snap permitido (use CTRL)',
		hideOption : 'Ocultar dibujos',
		textPlacement : 'Colocación',
		isMeasureMessage:'Esta etiqueta es una medida',
		west:'W',
		east:'E',
		north:'N',
		south:'S',
		arrow: 'Arrow',
		arrowNone: 'No',
		arrowBegin: 'Comienzo',
		arrowBeginEnd: 'Comienzo y fin',
		arrowEnd: 'Fin'
	}),
	"ar" : 1,
	"cs" : 1,
	"da" : 1,
	"de" : 1,
	"es" : 1,
	"et" : 1,
	"fi" : 1,
	"fr" : 1,
	"he" : 1,
	"it" : 1,
	"ja" : 1,
	"ko" : 1,
	"lt" : 1,
	"lv" : 1,
	"nb" : 1,
	"nl" : 1,
	"pl" : 1,
	"pt-br" : 1,
	"pt-pt" : 1,
	"ro" : 1,
	"ru" : 1,
	"sv" : 1,
	"th" : 1,
	"tr" : 1,
	"vi" : 1,
	"zh-cn" : 1
});
