define({
	root : ({
		addDistance: "Agregar unidad de longitud",
	    addArea: "Agregar unidad de área",
	    label: "Etiqueta",
	    abbr: "Abreviatura",
	    conversion: "Conversión",
	    actions: "Acciones",
	    areaUnits: "Unidades de área",
	    distanceUnits: "Unidades de longitud",
	    kilometers: "Kilómetros",
	    miles: "Millas",
	    meters: "Metros",
	    feet: "Pies",
	    yards: "Yardas",
	    squareKilometers: "Kilómetros cuadrados",
	    squareMiles: "Millas cuadradas",
	    acres: "Acres",
	    hectares: "Hectáreas",
	    squareMeters: "Metros cuadrados",
	    squareFeet: "Pies cuadrados",
	    squareYards: "Yardas cuadradas",
	    distance: "Distancias",
	    area: "Áreas",
	    kilometersAbbreviation: "km",
	    milesAbbreviation: "mi",
	    metersAbbreviation: "m",
	    feetAbbreviation: "ft",
	    yardsAbbreviation: "yd",
	    squareKilometersAbbreviation: "km²",
	    squareMilesAbbreviation: "mi²",
	    acresAbbreviation: "ac",
	    hectaresAbbreviation: "ha",
	    squareMetersAbbreviation: "m²",
	    squareFeetAbbreviation: "ft²",
	    squareYardsAbbreviation: "yd²",
	    defineUnits: "Define las unidades de medida.",
	    operationalLayer: "Agrega el dibujo como capa operativa del mapa."
	}),
	"ar" : 1,
	"cs" : 1,
	"da" : 1,
	"de" : 1,
	"el" : 1,
	"es" : 1,
	"et" : 1,
	"fi" : 1,
	"fr" : 1,
	"he" : 1,
	"it" : 1,
	"ja" : 1,
	"ko" : 1,
	"lt" : 1,
	"lv" : 1,
	"nb" : 1,
	"nl" : 1,
	"pl" : 1,
	"pt-br" : 1,
	"pt-pt" : 1,
	"ro" : 1,
	"ru" : 1,
	"sv" : 1,
	"th" : 1,
	"tr" : 1,
	"vi" : 1,
	"zh-cn" : 1,
	"zh-hk" : 1,
	"zh-tw" : 1
});
